[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  RAZORPAY_KEY_ID = "rzp_live_amIyo5XZmakZUK"
  RAZORPAY_KEY_SECRET = "LcsKwsb7c3CgCOXyiEDx17BZ"


[dev]
  functions = "netlify/functions"
  command = ""  # If you're using `npm start` to run your app locally
